// PackagesAdapter gate. NORMALIZE is exercised with INLINE payloads (the README path and
// the synthesized-metadata path) asserting the full post-processing our code controls:
// the title/abstract override, the `Package Metadata` section, section kinds + sortOrder,
// and the `source_metadata` JSON byte-for-byte. discover (official scope) runs network-free;
// the pure key/URL/license/abstract/etag helpers are unit-checked.
//
// NOTE: this is self-contained (no JS-oracle fixture bundle) so it needs no Fixtures/
// resource or Package.swift wiring — a deliberate divergence from the batch-2 draft, which
// pinned normalize against Fixtures/Packages/cases.json generated by the JS PackagesAdapter.

import Foundation
import Testing

@testable import ADBuilder

@Suite("PackagesAdapter — GitHub README packages")
struct PackagesAdapterTests {
    // MARK: - normalize (README path)

    // The canonical README-path input (repo + README + scope), shared by the split document/sections tests
    // below. Each `@Test` asserts against a typed intermediate (`doc` / `sections`) so its body type-checks
    // under the 250 ms budget — the single combined form tripped it (~266 ms).
    private func readmeInput() -> (key: String, payload: SourcePayload) {
        let input = #"""
            {
              "repo": {
                "name": "swift-nio",
                "full_name": "apple/swift-nio",
                "html_url": "https://github.com/apple/swift-nio",
                "description": "Event-driven network application framework",
                "language": null,
                "default_branch": "main",
                "topics": [],
                "owner": { "login": "apple" }
              },
              "readme": {
                "text": "# SwiftNIO\n\nSwiftNIO is a cross-platform asynchronous event-driven network application framework.\n\n## Overview\n\nDetails here.\n",
                "path": "README.md",
                "htmlUrl": "https://github.com/apple/swift-nio/blob/main/README.md",
                "downloadUrl": "https://raw.githubusercontent.com/apple/swift-nio/main/README.md"
              },
              "syncScope": "official",
              "fetchMode": "raw"
            }
            """#
        return ("packages/apple/swift-nio", SourcePayload.json(Array(input.utf8)))
    }

    @Test("normalize (README path) overrides title/abstract + emits ordered source metadata")
    func normalizeReadmeDocument() throws {
        let (key, payload) = readmeInput()
        // Document: repo full_name wins the title; the trimmed description overrides the abstract.
        let doc = try PackagesAdapter().normalize(key, payload).document
        #expect(doc.sourceType == "packages")
        #expect(doc.key == key)
        #expect(doc.kind == "package")
        #expect(doc.framework == "packages")
        #expect(doc.title == "apple/swift-nio")
        #expect(doc.abstractText == "Event-driven network application framework")
        #expect(doc.url == "https://github.com/apple/swift-nio")
        #expect(doc.language == nil)
        // source_metadata: insertion-ordered JSON, byte-identical to JSON.stringify.
        #expect(
            doc.sourceMetadata
                == #"{"package":true,"scope":"official","source":"raw","owner":"apple","repo":"swift-nio","fullName":"apple/swift-nio","defaultBranch":"main","stars":0,"forks":0,"openIssues":0,"topics":[],"archived":false,"fork":false,"homepage":null,"license":null,"primaryLanguage":null,"readmePath":"README.md","readmeUrl":"https://github.com/apple/swift-nio/blob/main/README.md","pushedAt":null,"updatedAt":null}"#
        )
        // packages contributes no cross-references (default extractReferences).
        #expect(PackagesAdapter().extractReferences(key, payload) == [])
    }

    @Test("normalize (README path) builds abstract + Overview + Package Metadata sections")
    func normalizeReadmeSections() throws {
        let (key, payload) = readmeInput()
        let page = try PackagesAdapter().normalize(key, payload)
        // Sections: abstract (overridden) + the README's `## Overview` + the Package Metadata block.
        let sections = page.sections
        #expect(sections.map(\.sectionKind) == ["abstract", "discussion", "discussion"])
        #expect(sections.map(\.sortOrder) == [0, 1, 2])
        #expect(sections[0].contentText == "Event-driven network application framework")
        #expect(sections[1].heading == "Overview")
        #expect(sections.last?.heading == "Package Metadata")
        #expect(
            sections.last?.contentText
                == "Repository: apple/swift-nio\n\nDefault branch: main\n\nREADME: README.md")
        #expect(page.relationships == [])
    }

    // MARK: - normalize (synthesized path — no README)

    @Test("normalize (no README) synthesizes markdown from repo metadata")
    func normalizeSynthesized() throws {
        let key = "packages/apple/swift-log"
        let input = #"""
            {
              "repo": {
                "name": "swift-log",
                "full_name": "apple/swift-log",
                "description": "A Logging API for Swift",
                "default_branch": "main",
                "topics": [],
                "owner": { "login": "apple" }
              },
              "readme": null,
              "syncScope": "official",
              "fetchMode": "raw"
            }
            """#
        let payload = SourcePayload.json(Array(input.utf8))
        let page = try PackagesAdapter().normalize(key, payload)

        #expect(page.document.title == "apple/swift-log")
        #expect(page.document.abstractText == "A Logging API for Swift")
        // html_url absent ⇒ URL is derived from full_name.
        #expect(page.document.url == "https://github.com/apple/swift-log")
        #expect(page.sections.map(\.sectionKind) == ["abstract", "discussion"])
        #expect(page.sections.map(\.sortOrder) == [0, 1])
        #expect(page.sections[0].contentText == "A Logging API for Swift")
        #expect(page.sections.last?.heading == "Package Metadata")
        #expect(page.sections.last?.contentText == "Repository: apple/swift-log\n\nDefault branch: main")
        #expect(
            page.document.sourceMetadata
                == #"{"package":true,"scope":"official","source":"raw","owner":"apple","repo":"swift-log","fullName":"apple/swift-log","defaultBranch":"main","stars":0,"forks":0,"openIssues":0,"topics":[],"archived":false,"fork":false,"homepage":null,"license":null,"primaryLanguage":null,"readmePath":null,"readmeUrl":null,"pushedAt":null,"updatedAt":null}"#
        )
    }

    @Test("normalize rejects a non-json payload")
    func normalizeRejectsNonJson() {
        #expect(throws: AdapterError.self) {
            _ = try PackagesAdapter().normalize("packages/apple/swift-nio", .markdown("nope"))
        }
    }

    // MARK: - discover (official scope, network-free)

    @Test("discover enumerates the curated official allowlist into packages/ keys + root")
    func discoverOfficial() async throws {
        let context = SourceContext(
            client: StubHTTPClient { _ in httpResponse(500) }, rateLimiter: instantRateLimiter())
        let discovery = try await PackagesAdapter().discover(context)
        #expect(discovery.keys.first == "packages/apple/swift-argument-parser")
        #expect(discovery.keys.contains("packages/swiftlang/swift-syntax"))
        #expect(discovery.keys.count == PackagesAdapter.officialPackages.count)
        #expect(discovery.keys.allSatisfy { $0.hasPrefix("packages/") })
        #expect(discovery.roots.map(\.slug) == ["packages"])
        #expect(discovery.roots.first?.source == "packages")
        #expect(discovery.roots.first?.kind == "collection")
    }

    // MARK: - pure key/url/license/abstract/etag helpers

    @Test("packageKey lowercases owner + repo under the packages slug")
    func packageKey() {
        #expect(PackagesAdapter.packageKey("Apple", "Swift-NIO") == "packages/apple/swift-nio")
    }

    @Test("parsePackageKey splits, parsePackageUrl parses github URLs")
    func keyAndUrl() throws {
        let parsed = try PackagesAdapter.parsePackageKey("packages/apple/swift-nio")
        #expect(parsed.owner == "apple" && parsed.repo == "swift-nio")
        #expect(throws: AdapterError.self) { _ = try PackagesAdapter.parsePackageKey("packages/apple") }

        #expect(PackagesAdapter.parsePackageUrl("https://github.com/apple/swift-nio.git")?.repo == "swift-nio")
        #expect(PackagesAdapter.parsePackageUrl("https://github.com/apple/swift-nio/")?.owner == "apple")
        #expect(PackagesAdapter.parsePackageUrl("https://example.com/apple/swift-nio") == nil)
    }

    @Test("normalizeLicense prefers spdx, falls back to name on NOASSERTION")
    func license() {
        #expect(PackagesAdapter.normalizeLicense(.init(spdx_id: "MIT", name: "MIT License")) == "MIT")
        #expect(PackagesAdapter.normalizeLicense(.init(spdx_id: "NOASSERTION", name: "Custom")) == "Custom")
        #expect(PackagesAdapter.normalizeLicense(nil) == nil)
    }

    @Test("extractAbstractFromMarkdown returns the first prose paragraph after the H1")
    func abstract() {
        let markdown = "# Title\n\n[![badge](x)](y)\n\nThe real abstract paragraph.\n"
        #expect(PackagesAdapter.extractAbstractFromMarkdown(markdown) == "The real abstract paragraph.")
        #expect(PackagesAdapter.extractAbstractFromMarkdown(nil) == nil)
    }

    @Test("parseCompositeEtag reads the raw composite validator")
    func compositeEtag() {
        let state = PackagesAdapter.parseCompositeEtag(
            #"{"source":"raw","repo":null,"readme":"W/\"abc\"","branch":"main","readmeFilename":"README.md"}"#)
        #expect(state.source == "raw")
        #expect(state.readme == "W/\"abc\"")
        #expect(state.branch == "main")
        #expect(state.readmeFilename == "README.md")
        // A bare (non-JSON) validator degrades to the api repo ETag.
        let bare = PackagesAdapter.parseCompositeEtag("plainetag")
        #expect(bare.source == "api")
        #expect(bare.repo == "plainetag")
    }
}
