// Byte-pinned against the JS implementation (the expectations below were
// generated by running render-markdown.js / render-text.js / renderer.js
// on these exact inputs). The committed fixture corpus + full-corpus A/B
// are the real parity gates; these pin the constructed edge cases.

import Testing

@testable import ADBase
@testable import ADContent

struct DocMarkdownTests {
  static let doc = ContentDocument(
    key: "swiftui/view", title: "View", framework: "swiftui", frameworkDisplay: nil,
    role: "symbol", roleHeading: "Protocol",
    platformsJson: #"{"ios":"13.0","macos":"10.15","weird":null}"#)

  static let sections = [
    ContentSection(
      sectionKind: "discussion", contentText: "Line one\nline two\n\nPara two.", sortOrder: 2),
    ContentSection(
      sectionKind: "abstract", contentText: "  A type that represents a view.  ", sortOrder: 0),
    ContentSection(
      sectionKind: "declaration", contentText: "",
      contentJson: #"[{"tokens":[{"text":"protocol "},{"text":"View"}],"languages":["swift"]}]"#,
      sortOrder: 1),
    ContentSection(
      sectionKind: "topics", contentText: "",
      contentJson: #"[{"title":"Creating","items":[{"key":"swiftui/text","title":"Text"},{"title":"No key"}]}]"#,
      sortOrder: 3),
    ContentSection(sectionKind: "custom_kind", contentText: "custom body", sortOrder: 4),
    ContentSection(
      sectionKind: "parameters", contentText: "",
      contentJson:
        #"[{"name":"content","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The  content"}]}]},{}]"#,
      sortOrder: 5),
  ]

  @Test func fullDocumentMatchesJs() {
    let want = """
      ---
      title: View
      framework: swiftui
      role: symbol
      role_heading: Protocol
      platforms: [iOS 13.0+, macOS 10.15+, weird]
      path: swiftui/view
      ---

      # View

      A type that represents a view.

      ## Declaration

      ```swift
      protocol View
      ```

      ## Overview

      Line one line two

      Para two.

      ## Topics

      ### Creating

      - [Text](swiftui/text.md)
      - No key

      ## Custom Kind

      custom body

      ## Parameters

      - `content`: The content
      - `Value`:

      """
    #expect(DocMarkdown.render(document: Self.doc, sections: Self.sections) == want)
  }

  @Test func bareDocumentSkipsFrontMatterAndTitle() {
    let rendered = DocMarkdown.render(
      document: Self.doc, sections: Self.sections, includeFrontMatter: false, includeTitle: false)
    #expect(rendered.hasPrefix("A type that represents a view.\n"))
    #expect(!rendered.contains("---"))
    #expect(!rendered.contains("# View"))
  }

  @Test func plainTextMatchesJs() {
    let document = PlainTextDocument(
      title: "View", abstractText: "Abstract here", declarationText: "protocol View",
      headings: "h1\nh2")
    let sections = [
      PlainTextSection(heading: "Over", contentText: "Body\n\n\n\ntext", sortOrder: 1),
      PlainTextSection(heading: "", contentText: "   ", sortOrder: 0),
    ]
    let want = "View\n\nAbstract here\n\nprotocol View\n\nh1\nh2\n\nOver\nBody\n\ntext"
    #expect(PlainText.render(document: document, sections: sections) == want)
  }
}

struct PageMarkdownTests {
  @Test func pageMatchesJs() throws {
    let pageJson = #"""
      {"metadata":{"title":"View","roleHeading":"Protocol","role":"symbol","modules":[{"name":"SwiftUI"}],"platforms":[{"name":"iOS","introducedAt":"13.0"},{"name":"macOS"},{"introducedAt":"1.0"}]},"abstract":[{"type":"text","text":"A view "},{"type":"codeVoice","code":"V"}],"references":{"doc://x/documentation/swiftui/text":{"title":"Text","url":"/documentation/swiftui/text"}},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol View"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"doc://x/documentation/swiftui/text"},{"type":"text","text":" and "},{"type":"reference","identifier":"doc://x/documentation/swiftui/missing","isActive":false}]},{"type":"codeListing","syntax":"swift","code":["let a = 1","print(a)"]},{"type":"aside","style":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Note this."}]}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Item one"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Item two"}]}]}]},{"type":"table","rows":[{"cells":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"H1"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"H2"}]}]}]},{"cells":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"a\nb"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"c"}]}]}]}]}]}],"topicSections":[{"title":"Creating","identifiers":["doc://x/documentation/swiftui/text","doc://x/not-a-doc"]}]}
      """#
    let want = """
      ---
      title: View
      framework: SwiftUI
      role: symbol
      role_heading: Protocol
      platforms: [iOS 13.0+, macOS, undefined 1.0+]
      path: swiftui/view
      ---

      # View

      A view `V`

      ## Declaration

      ```swift
      protocol View
      ```

      ## Overview

      See [Text](text.md) and `doc://x/documentation/swiftui/missing`

      ```swift
      let a = 1
      print(a)
      ```

      > **Important:** Note this.

      - Item one
      - Item two

      | H1 | H2 |
      | --- | --- |
      | a b | c |

      ## Topics

      ### Creating

      - [Text](text.md)
      - doc://x/not-a-doc

      """
    let parsed = try Json.parse(Array(pageJson.utf8))
    #expect(PageMarkdown.render(json: parsed, canonicalPath: "swiftui/view") == want)
  }

  @Test func relativePathMatchesJs() {
    #expect(PageMarkdown.relativePath(from: "swiftui/view", to: "swiftui/text") == "text")
    #expect(PageMarkdown.relativePath(from: "swiftui/view", to: "swiftui/view") == "view")
    #expect(PageMarkdown.relativePath(from: "swiftui/view/body", to: "uikit/uiview") == "../../uikit/uiview")
    #expect(PageMarkdown.relativePath(from: "a", to: "b/c/d") == "b/c/d")
    #expect(PageMarkdown.relativePath(from: "", to: "x/y") == "x/y")
  }
}

struct IdentifierTests {
  @Test func normalizeMatchesJs() {
    #expect(Identifier.normalize("doc://com.apple.SwiftUI/documentation/SwiftUI/View") == "swiftui/view")
    #expect(Identifier.normalize("doc://com.apple.design/design/human-interface-guidelines/color") == "design/human-interface-guidelines/color")
    #expect(Identifier.normalize("/documentation/SwiftUI/View") == "swiftui/view")
    #expect(Identifier.normalize("documentation/UIKit/UIView/") == "uikit/uiview")
    #expect(Identifier.normalize("/design/foo") == "design/foo")
    #expect(Identifier.normalize("/app-store-review/3.1.1") == "app-store-review/3.1.1")
    #expect(Identifier.normalize("page#section") == "page")
    #expect(Identifier.normalize("https://example.com/x") == nil)
    #expect(Identifier.normalize("swift/int/.../init") == nil)
    #expect(Identifier.normalize("a//b") == nil)
    #expect(Identifier.normalize("") == nil)
    #expect(Identifier.normalize("#frag") == nil)
    #expect(Identifier.normalize("ΣWIFT/View") == "σwift/view")
  }

  @Test func humanizeAndHelpers() {
    #expect(JsString.humanize("custom_kind") == "Custom Kind")
    #expect(JsString.humanize("already Big") == "Already Big")
    #expect(JsString.humanize("x9 9x _a") == "X9 9x  A")
    #expect(JsString.trim("\u{FEFF} x \u{00A0}") == "x")
    #expect(JsString.normalizeParagraphs("a\nb\n\n\nc") == "a b\n\nc")
    #expect(JsString.collapseWhitespaceRuns("a \t\n b") == "a b")
  }
}
