import Testing

@testable import ADOps

// The BYTE-PARITY GATE. render-all over the 11 committed ops/*.tpl files must
// emit plists / Caddyfile / cloudflared-yaml / sudoers BYTE-IDENTICAL to the JS
// oracle (ops/cmd/render-all.js). Expected bytes were generated by running the
// real ops JS over Fixtures/fixture.env and pinned under Fixtures/expected/.

/// template basename → (rendered output basename, allowlisted-but-empty vars the
/// JS reports `unresolved`). This is the JS oracle's contract (manifest.json).
private struct ParityCase {
    let template: String
    let output: String
    let unresolved: [String]
}

private let parityCases: [ParityCase] = [
    ParityCase(template: "Caddyfile.tpl", output: "Caddyfile", unresolved: []),
    ParityCase(template: "config-mcp.yml.tpl", output: "config-mcp.yml", unresolved: []),
    ParityCase(template: "config.yml.tpl", output: "config.yml", unresolved: []),
    ParityCase(
        template: "apple-docs.autoroll.plist.tpl",
        output: "mt.everest.apple-docs.autoroll.plist", unresolved: []),
    ParityCase(
        template: "apple-docs.mcp.plist.tpl", output: "mt.everest.apple-docs.mcp.plist",
        unresolved: ["APPLE_DOCS_NATIVE"]),
    ParityCase(
        template: "apple-docs.proxy.plist.tpl", output: "mt.everest.apple-docs.proxy.plist",
        unresolved: []),
    ParityCase(
        template: "apple-docs.watchdog.plist.tpl",
        output: "mt.everest.apple-docs.watchdog.plist", unresolved: []),
    ParityCase(
        template: "apple-docs.web.plist.tpl", output: "mt.everest.apple-docs.web.plist",
        unresolved: ["APPLE_DOCS_NATIVE"]),
    ParityCase(
        template: "cloudflared.apple-docs-mcp.plist.tpl",
        output: "mt.everest.apple-docs.cloudflared.mcp.plist", unresolved: []),
    ParityCase(
        template: "cloudflared.apple-docs.plist.tpl",
        output: "mt.everest.apple-docs.cloudflared.web.plist", unresolved: []),
    ParityCase(
        template: "sudoers.apple-docs-launchctl.tpl", output: "sudoers.apple-docs-launchctl",
        unresolved: [])
]

/// Build the fully-derived var bag from the canonical fixture .env, using the
/// Swift OpsEnv parse + derive path (so the gate also proves OpsEnv derivation).
private func fixtureEnvVars() throws -> [String: String] {
    var vars = OpsEnv.parse(Fixtures.text("fixture.env"))
    try OpsEnv.applyDerived(&vars)
    return vars
}

@Test func parityGateRendersEveryTemplateByteIdentical() throws {
    let vars = try fixtureEnvVars()
    #expect(parityCases.count == 11)
    for testCase in parityCases {
        let template = Fixtures.bytes("templates/\(testCase.template)")
        let expected = Fixtures.bytes("expected/\(testCase.output)")
        let result = RenderTemplate.render(bytes: template, env: vars, allowed: allowedVarsSet)
        // Byte-exact equality — the whole point of the gate.
        #expect(
            result.contentBytes == expected,
            "byte mismatch rendering \(testCase.template) → \(testCase.output)")
        #expect(
            result.unresolved == testCase.unresolved,
            "unresolved mismatch for \(testCase.template)")
        #expect(result.ignored.isEmpty, "unexpected ignored placeholders in \(testCase.template)")
    }
}

@Test func parityGateOutputNameMappingMatchesJS() throws {
    let vars = try fixtureEnvVars()
    let opsDir = "/opt/apple-docs/ops"
    for testCase in parityCases {
        // Launchd plists live under ops/launchd/ in the real layout; sudoers +
        // caddy + cloudflared are elsewhere. Reconstruct the real template path
        // so resolveOutput's launchd-dir branch is exercised.
        let templatePath = realTemplatePath(testCase.template, opsDir: opsDir)
        let resolved = RenderAll.resolveOutput(
            template: templatePath, opsDir: opsDir, vars: vars)
        #expect(
            lastPathComponent(resolved) == testCase.output,
            "output name mismatch for \(testCase.template)")
    }
}

/// The real ops path for a committed template basename.
private func realTemplatePath(_ base: String, opsDir: String) -> String {
    if base == "Caddyfile.tpl" { return "\(opsDir)/caddy/\(base)" }
    if base.hasSuffix(".yml.tpl") { return "\(opsDir)/cloudflared/\(base)" }
    return "\(opsDir)/launchd/\(base)"
}
