import Testing

@testable import ADWebBuild

// Expected strings are byte-exact captures of the JS templates (generated by
// running `buildHead`/`buildScripts` from src/web/templates.js). Single-line
// literals (cheap to type-check); compared with `#expect`.

private let staticConfig = SiteConfig(baseUrl: "https://x.test", siteName: "Docs", assetVersion: "v1", bundled: true)

@Test func buildHeadByteExact() {
    let actual = PageShell.buildHead(
        config: staticConfig, title: "Hi <there>", description: "A's desc",
        canonical: "https://x.test/p", ogType: "article")
    let expected =
        "<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>Hi &lt;there&gt;</title>\n  <meta name=\"description\" content=\"A&#x27;s desc\">\n  <link rel=\"canonical\" href=\"https://x.test/p\">\n  <meta name=\"robots\" content=\"index, follow, max-image-preview:large\">\n  <meta property=\"og:type\" content=\"article\">\n  <meta property=\"og:title\" content=\"Hi &lt;there&gt;\">\n  <meta property=\"og:url\" content=\"https://x.test/p\">\n  <meta property=\"og:site_name\" content=\"Docs\">\n  <meta property=\"og:description\" content=\"A&#x27;s desc\">\n  <meta name=\"twitter:card\" content=\"summary\">\n  <meta name=\"twitter:title\" content=\"Hi &lt;there&gt;\">\n  <meta name=\"twitter:description\" content=\"A&#x27;s desc\">\n  <link rel=\"preload\" href=\"https://x.test/assets/style.css?v=v1\" as=\"style\">\n  <link rel=\"stylesheet\" href=\"https://x.test/assets/style.css?v=v1\">\n  <link rel=\"search\" type=\"application/opensearchdescription+xml\" title=\"Docs\" href=\"https://x.test/opensearch.xml\">\n  <script src=\"https://x.test/assets/core.js?v=v1\" defer></script>\n</head>"
    #expect(actual == expected)
}

@Test func buildHeadNoDescription() {
    let actual = PageShell.buildHead(config: staticConfig, title: "Plain", canonical: "https://x.test/q")
    let expected =
        "<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>Plain</title>\n  \n  <link rel=\"canonical\" href=\"https://x.test/q\">\n  <meta name=\"robots\" content=\"index, follow, max-image-preview:large\">\n  <meta property=\"og:type\" content=\"website\">\n  <meta property=\"og:title\" content=\"Plain\">\n  <meta property=\"og:url\" content=\"https://x.test/q\">\n  <meta property=\"og:site_name\" content=\"Docs\">\n  <meta name=\"twitter:card\" content=\"summary\">\n  <meta name=\"twitter:title\" content=\"Plain\">\n  <link rel=\"preload\" href=\"https://x.test/assets/style.css?v=v1\" as=\"style\">\n  <link rel=\"stylesheet\" href=\"https://x.test/assets/style.css?v=v1\">\n  <link rel=\"search\" type=\"application/opensearchdescription+xml\" title=\"Docs\" href=\"https://x.test/opensearch.xml\">\n  <script src=\"https://x.test/assets/core.js?v=v1\" defer></script>\n</head>"
    #expect(actual == expected)
}

@Test func buildScriptsBundled() {
    let actual = PageShell.buildScripts(staticConfig, ["core", "listing"])
    #expect(actual == "<script src=\"https://x.test/assets/listing.js?v=v1\" defer></script>")
}

@Test func buildScriptsDev() {
    let dev = SiteConfig(baseUrl: "", siteName: "Docs", assetVersion: nil, bundled: false)
    let actual = PageShell.buildScripts(dev, ["core", "listing"])
    let expected =
        "<script src=\"/assets/theme.js\" defer></script>\n<script src=\"/assets/search.js\" defer></script>\n<script src=\"/assets/page-toc.js\" defer></script>\n<script src=\"/assets/collection-filters.js\" defer></script>\n<script src=\"/assets/tree-view.js\" defer></script>"
    #expect(actual == expected)
}
