import Testing

@testable import ADWebBuild

// Expected strings are byte-exact captures of the JS templates (generated by
// running `buildHead`/`buildScripts` from src/web/templates.js). Single-line
// literals (cheap to type-check); compared with `#expect`.

private let staticConfig = SiteConfig(baseUrl: "https://x.test", siteName: "Docs", assetVersion: "v1", bundled: true)

@Test func buildHeadByteExact() {
    let actual = PageShell.buildHead(
        config: staticConfig, title: "Hi <there>", description: "A's desc",
        canonical: "https://x.test/p", ogType: "article")
    let expected =
        "<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>Hi &lt;there&gt;</title>\n  <meta name=\"description\" content=\"A&#x27;s desc\">\n  <link rel=\"canonical\" href=\"https://x.test/p\">\n  <meta name=\"robots\" content=\"index, follow, max-image-preview:large\">\n  <meta property=\"og:type\" content=\"article\">\n  <meta property=\"og:title\" content=\"Hi &lt;there&gt;\">\n  <meta property=\"og:url\" content=\"https://x.test/p\">\n  <meta property=\"og:site_name\" content=\"Docs\">\n  <meta property=\"og:description\" content=\"A&#x27;s desc\">\n  <meta name=\"twitter:card\" content=\"summary\">\n  <meta name=\"twitter:title\" content=\"Hi &lt;there&gt;\">\n  <meta name=\"twitter:description\" content=\"A&#x27;s desc\">\n  <link rel=\"preload\" href=\"https://x.test/assets/style.css?v=v1\" as=\"style\">\n  <link rel=\"stylesheet\" href=\"https://x.test/assets/style.css?v=v1\">\n  <link rel=\"search\" type=\"application/opensearchdescription+xml\" title=\"Docs\" href=\"https://x.test/opensearch.xml\">\n  <script src=\"https://x.test/assets/core.js?v=v1\" defer></script>\n</head>"
    #expect(actual == expected)
}

@Test func buildHeadNoDescription() {
    let actual = PageShell.buildHead(config: staticConfig, title: "Plain", canonical: "https://x.test/q")
    let expected =
        "<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>Plain</title>\n  \n  <link rel=\"canonical\" href=\"https://x.test/q\">\n  <meta name=\"robots\" content=\"index, follow, max-image-preview:large\">\n  <meta property=\"og:type\" content=\"website\">\n  <meta property=\"og:title\" content=\"Plain\">\n  <meta property=\"og:url\" content=\"https://x.test/q\">\n  <meta property=\"og:site_name\" content=\"Docs\">\n  <meta name=\"twitter:card\" content=\"summary\">\n  <meta name=\"twitter:title\" content=\"Plain\">\n  <link rel=\"preload\" href=\"https://x.test/assets/style.css?v=v1\" as=\"style\">\n  <link rel=\"stylesheet\" href=\"https://x.test/assets/style.css?v=v1\">\n  <link rel=\"search\" type=\"application/opensearchdescription+xml\" title=\"Docs\" href=\"https://x.test/opensearch.xml\">\n  <script src=\"https://x.test/assets/core.js?v=v1\" defer></script>\n</head>"
    #expect(actual == expected)
}

@Test func buildScriptsBundled() {
    let actual = PageShell.buildScripts(staticConfig, ["core", "listing"])
    #expect(actual == "<script src=\"https://x.test/assets/listing.js?v=v1\" defer></script>")
}

@Test func buildScriptsDev() {
    let dev = SiteConfig(baseUrl: "", siteName: "Docs", assetVersion: nil, bundled: false)
    let actual = PageShell.buildScripts(dev, ["core", "listing"])
    let expected =
        "<script src=\"/assets/theme.js\" defer></script>\n<script src=\"/assets/search.js\" defer></script>\n<script src=\"/assets/page-toc.js\" defer></script>\n<script src=\"/assets/collection-filters.js\" defer></script>\n<script src=\"/assets/tree-view.js\" defer></script>"
    #expect(actual == expected)
}

@Test func buildHeaderByteExact() {
    let actual = PageShell.buildHeader(SiteConfig(baseUrl: "https://x.test", siteName: "Docs"))
    let expected =
        "<header class=\"site-header\">\n  <nav class=\"site-nav\">\n    <a class=\"site-name\" href=\"https://x.test/\">Docs</a>\n    <div class=\"search-container\">\n      <input class=\"search-input\" type=\"search\" role=\"combobox\" aria-haspopup=\"listbox\" placeholder=\"Search…\" aria-label=\"Search documentation\" autocomplete=\"off\" aria-expanded=\"false\" aria-controls=\"search-listbox\" aria-activedescendant=\"\" aria-autocomplete=\"list\">\n      <button class=\"search-clear\" type=\"button\" aria-label=\"Clear search\" hidden>&times;</button>\n      <div class=\"search-dropdown\" id=\"search-listbox\" hidden></div>\n      <div id=\"header-search-status\" aria-live=\"assertive\" class=\"sr-only\"></div>\n    </div>\n    <fieldset class=\"theme-switcher\" role=\"radiogroup\" aria-label=\"Color scheme\">\n      <button class=\"theme-option\" type=\"button\" role=\"radio\" data-theme-value=\"light\" aria-label=\"Light theme\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\"><circle cx=\"8\" cy=\"8\" r=\"3\"/><path d=\"M8 1.5v2M8 12.5v2M1.5 8h2M12.5 8h2M3.4 3.4l1.4 1.4M11.2 11.2l1.4 1.4M3.4 12.6l1.4-1.4M11.2 4.8l1.4-1.4\"/></svg></button>\n      <button class=\"theme-option\" type=\"button\" role=\"radio\" data-theme-value=\"auto\" aria-label=\"System theme\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\"><circle cx=\"8\" cy=\"8\" r=\"5.5\"/><path d=\"M8 2.5v11\" fill=\"currentColor\"/><path d=\"M8 2.5A5.5 5.5 0 0 1 8 13.5\" fill=\"currentColor\"/></svg></button>\n      <button class=\"theme-option\" type=\"button\" role=\"radio\" data-theme-value=\"dark\" aria-label=\"Dark theme\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\"><path d=\"M13 9.5A5.5 5.5 0 1 1 6.5 3 4.5 4.5 0 0 0 13 9.5z\"/></svg></button>\n    </fieldset>\n  </nav>\n</header>"
    #expect(actual == expected)
}

@Test func buildFooterFull() {
    let config = SiteConfig(buildDate: "2026-06-30", snapshotTag: "snapshot-20260630", buildMacos: "26.0", commitHash: "abc1234")
    let actual = PageShell.buildFooter(config)
    let expected =
        "<footer class=\"site-footer\">\n  <p>\n    Built on 2026-06-30 &middot; <span class=\"footer-snapshot\">Snapshot <a href=\"https://github.com/g-cqd/apple-docs/releases/tag/snapshot-20260630\" rel=\"noopener noreferrer\"><code>snapshot-20260630</code></a> (macOS 26.0)</span> &middot; <span class=\"footer-commit\">Commit <a href=\"https://github.com/g-cqd/apple-docs/commit/abc1234\" rel=\"noopener noreferrer\"><code>abc1234</code></a></span>\n    &middot; by <a href=\"https://github.com/g-cqd\" rel=\"noopener noreferrer\">@g-cqd</a>\n    &middot; based on <a href=\"https://developer.apple.com\" rel=\"noopener noreferrer\">Apple Developer Documentation</a>\n  </p>\n</footer>"
    #expect(actual == expected)
}

@Test func buildFooterMinimal() {
    let actual = PageShell.buildFooter(SiteConfig(buildDate: "2026-06-30"))
    let expected =
        "<footer class=\"site-footer\">\n  <p>\n    Built on 2026-06-30\n    &middot; by <a href=\"https://github.com/g-cqd\" rel=\"noopener noreferrer\">@g-cqd</a>\n    &middot; based on <a href=\"https://developer.apple.com\" rel=\"noopener noreferrer\">Apple Developer Documentation</a>\n  </p>\n</footer>"
    #expect(actual == expected)
}
